development:
  adapter: mysql
  database: laika
  username: laika
  password: laika
  host: 127.0.0.1
  
production:
  adapter: mysql
  database: laika
  username: laika
  password: laika
  host: 127.0.0.1